### ISSUE TITLE
Fails with jest 27

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/abortable-promise-cache#24]
Upgrading to jest 27 causes an Uncaught promise: Error: aborted

This branch has a "fix" but it is unclear if it is still testing the same behavior

https://github.com/GMOD/abortable-promise-cache/tree/fails_jest27

Specific test
```
yarn test -t 'cache 2 requests, both aborted, one pre-aborted, and fill aborted'
```

**Comment by cmdcolin** [comment]
This actually happens on jest 24.9 (what we are currently on)

Just running "yarn upgrade" on the current master branch causes it to fail with this same error

**Comment by rbuels** [comment]
My first thought is that this might come from promises that are evicted or
resolved and later aborted.
